### ISSUE TITLE
wrong import with latest graphql

### ISSUE THREAD

**Issue by rkoberg** [davidchang/graphql-pokedex-api#1]
You need to change your imports for schema.js and schemaTypes.js from:

```
} from 'graphql/lib/type':
```

to:

```
} from 'graphql';
```

**Comment by noscripter** [comment]
+1

**Comment by hasdavidc** [comment]
Thanks for the issue, addressed here: https://github.com/davidchang/graphql-pokedex-api/commit/f51bc61d0906d45c3cf1d89120e12322d63081a7 Closing
